name: Versionamento

'on':
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    version:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
          - name: Version
            uses: paulhatch/semantic-version@v5.2.1
            id: version
            with:
              tag_prefix: "v"
          
          - name: Print Diagnostic Output
            run: echo "$DEBUG_OUTPUT"
            env:
              DEBUG_OUTPUT: ${{ steps.version.outputs.version }}