name: Versionamento

on:
  pull_request:
    branches: [ "main" ]
    types:
      - closed
      
jobs:
  version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout       
        uses: actions/checkout@v2

      - name: Versionar
        uses: paulhatch/semantic-version@v5.3.0
        with:
          version_from_branch: true

      - name: Commit
        run: |
          git add .
          git commit -m "Atualizar versão"

      - name: Push
        run: |
          git push origin main