name: Versionamento

'on':
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    version:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 0

          - name: Versionar
            uses: paulhatch/semantic-version@v5.3.0
            with:
              # The prefix to use to identify tags
              tag_prefix: "v"

          - name: add tag
            run: |
              echo "Versão: ${{ steps.Versionar.outputs.version }}"
              echo "Número da versão: ${{ steps.Versionar.outputs.major }}.${{ steps.Versionar.outputs.minor }}.${{ steps.Versionar.outputs.patch }}"
              echo "Pre-release: ${{ steps.Versionar.outputs.prerelease }}"
              echo "Build: ${{ steps.Versionar.outputs.build }}"

          - name: config user
            run: |
                git config --global user.email "devops@roit.com.br"
                git config --global user.name "DevOps Squad | ROIT"
        
          - name: Commit
            run: |
                git add .
                git commit -m "Atualizar versão"
        
          - name: Push
            run: |
                git push origin main