name: Versionamento

'on':
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    version:
        if: github.event.pull_request.merged == true
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
              fetch-depth: 0

          - name: config user
            run: |
                git config --global user.email "devops@roit.com.br"
                git config --global user.name "DevOps Squad | ROIT" 

          - name: Version
            uses: paulhatch/semantic-version@v5.3.0
            id: version
            with:
              tag_prefix: "v"
              major_pattern: "BREAKING CHANGE:"
              minor_pattern: "feat("
         
          - name: Add tag
            run: |
              echo "$NEW_TAG"
              git tag -a $NEW_TAG -m "new version $NEW_TAG"
              git push origin $NEW_TAG
            env:
              NEW_TAG: ${{ steps.version.outputs.version }}